# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amazon/mt8135-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amazon/mt8135-common

PRODUCT_COPY_FILES += \
    vendor/amazon/mt8135-common/proprietary/bin/6620_launcher:$(TARGET_COPY_OUT_SYSTEM)/bin/6620_launcher \
    vendor/amazon/mt8135-common/proprietary/bin/6620_wmt_concurrency:$(TARGET_COPY_OUT_SYSTEM)/bin/6620_wmt_concurrency \
    vendor/amazon/mt8135-common/proprietary/bin/6620_wmt_lpbk:$(TARGET_COPY_OUT_SYSTEM)/bin/6620_wmt_lpbk \
    vendor/amazon/mt8135-common/proprietary/bin/amzn_dha_hmac:$(TARGET_COPY_OUT_SYSTEM)/bin/amzn_dha_hmac \
    vendor/amazon/mt8135-common/proprietary/bin/amzn_dha_tool:$(TARGET_COPY_OUT_SYSTEM)/bin/amzn_dha_tool \
    vendor/amazon/mt8135-common/proprietary/bin/amzn_drmprov_check:$(TARGET_COPY_OUT_SYSTEM)/bin/amzn_drmprov_check \
    vendor/amazon/mt8135-common/proprietary/bin/amzn_drmprov_tool:$(TARGET_COPY_OUT_SYSTEM)/bin/amzn_drmprov_tool \
    vendor/amazon/mt8135-common/proprietary/bin/devicetype_service:$(TARGET_COPY_OUT_SYSTEM)/bin/devicetype_service \
    vendor/amazon/mt8135-common/proprietary/bin/idme:$(TARGET_COPY_OUT_SYSTEM)/bin/idme \
    vendor/amazon/mt8135-common/proprietary/bin/kisd:$(TARGET_COPY_OUT_SYSTEM)/bin/kisd \
    vendor/amazon/mt8135-common/proprietary/bin/nvram_agent_binder:$(TARGET_COPY_OUT_SYSTEM)/bin/nvram_agent_binder \
    vendor/amazon/mt8135-common/proprietary/bin/thermal_manager:$(TARGET_COPY_OUT_SYSTEM)/bin/thermal_manager \
    vendor/amazon/mt8135-common/proprietary/bin/wlan_loader:$(TARGET_COPY_OUT_SYSTEM)/bin/wlan_loader \
    vendor/amazon/mt8135-common/proprietary/bin/wmt_loader:$(TARGET_COPY_OUT_SYSTEM)/bin/wmt_loader \
    vendor/amazon/mt8135-common/proprietary/bin/wpa_supplicant:$(TARGET_COPY_OUT_SYSTEM)/bin/wpa_supplicant \
    vendor/amazon/mt8135-common/proprietary/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/.tp/thermal.conf \
    vendor/amazon/mt8135-common/proprietary/etc/.tp/thermal.encrypt.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/.tp/thermal.encrypt.conf \
    vendor/amazon/mt8135-common/proprietary/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/.tp/thermal.off.conf \
    vendor/amazon/mt8135-common/proprietary/etc/.tp/thermal.policy.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/.tp/thermal.policy.conf \
    vendor/amazon/mt8135-common/proprietary/etc/kisd_starter.sh:$(TARGET_COPY_OUT_SYSTEM)/etc/kisd_starter.sh \
    vendor/amazon/mt8135-common/proprietary/lib/hw/amzn_dha.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/amzn_dha.mt8135.so \
    vendor/amazon/mt8135-common/proprietary/lib/hw/amzn_drmprov.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/amzn_drmprov.mt8135.so \
    vendor/amazon/mt8135-common/proprietary/lib/hw/gps.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gps.mt8135.so \
    vendor/amazon/mt8135-common/proprietary/lib/hw/keystore.amzn.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/keystore.amzn.mt8135.so \
    vendor/amazon/mt8135-common/proprietary/lib/hw/keystore.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/keystore.mt8135.so \
    vendor/amazon/mt8135-common/proprietary/lib/hw/thermal.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/thermal.mt8135.so \
    vendor/amazon/mt8135-common/proprietary/lib/libMtkOmxAIVPlayer.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libMtkOmxAIVPlayer.so \
    vendor/amazon/mt8135-common/proprietary/lib/libMtkOmxCore.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libMtkOmxCore.so \
    vendor/amazon/mt8135-common/proprietary/lib/libMtkOmxMp3Dec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libMtkOmxMp3Dec.so \
    vendor/amazon/mt8135-common/proprietary/lib/libMtkOmxVdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libMtkOmxVdec.so \
    vendor/amazon/mt8135-common/proprietary/lib/libMtkOmxVenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libMtkOmxVenc.so \
    vendor/amazon/mt8135-common/proprietary/lib/lib_uree_mtk_modular_drm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_uree_mtk_modular_drm.so \
    vendor/amazon/mt8135-common/proprietary/lib/lib_uree_mtk_video_secure_al.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_uree_mtk_video_secure_al.so \
    vendor/amazon/mt8135-common/proprietary/lib/libaudio_customization.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudio_customization.so \
    vendor/amazon/mt8135-common/proprietary/lib/libaudiosetting.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiosetting.so \
    vendor/amazon/mt8135-common/proprietary/lib/libbessound_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbessound_mtk.so \
    vendor/amazon/mt8135-common/proprietary/lib/libblisrc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libblisrc.so \
    vendor/amazon/mt8135-common/proprietary/lib/libbwc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbwc.so \
    vendor/amazon/mt8135-common/proprietary/lib/libcameraservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcameraservice.so \
    vendor/amazon/mt8135-common/proprietary/lib/libdpframework.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdpframework.so \
    vendor/amazon/mt8135-common/proprietary/lib/libdpframework_os.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdpframework_os.so \
    vendor/amazon/mt8135-common/proprietary/lib/libdpframework_plat.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdpframework_plat.so \
    vendor/amazon/mt8135-common/proprietary/lib/libdrmmtkutil.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdrmmtkutil.so \
    vendor/amazon/mt8135-common/proprietary/lib/libgpu_aux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgpu_aux.so \
    vendor/amazon/mt8135-common/proprietary/lib/libgralloc_extra.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgralloc_extra.so \
    vendor/amazon/mt8135-common/proprietary/lib/libhwm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhwm.so \
    vendor/amazon/mt8135-common/proprietary/lib/libion_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libion_mtk.so \
    vendor/amazon/mt8135-common/proprietary/lib/libm4u.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libm4u.so \
    vendor/amazon/mt8135-common/proprietary/lib/libmtk_drvb.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtk_drvb.so \
    vendor/amazon/mt8135-common/proprietary/lib/libnvram.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnvram.so \
    vendor/amazon/mt8135-common/proprietary/lib/libsched.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsched.so \
    vendor/amazon/mt8135-common/proprietary/lib/libspeech_enh_lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libspeech_enh_lib.so \
    vendor/amazon/mt8135-common/proprietary/lib/libstagefrighthw.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefrighthw.so \
    vendor/amazon/mt8135-common/proprietary/lib/libthermalservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libthermalservice.so \
    vendor/amazon/mt8135-common/proprietary/lib/libtz_uree.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libtz_uree.so \
    vendor/amazon/mt8135-common/proprietary/lib/liburee_meta_drmkeyinstall_v2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/liburee_meta_drmkeyinstall_v2.so \
    vendor/amazon/mt8135-common/proprietary/lib/libvcodec_utility.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvcodec_utility.so \
    vendor/amazon/mt8135-common/proprietary/lib/libvcodecdrv.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvcodecdrv.so \
    vendor/amazon/mt8135-common/proprietary/vendor/bin/pvrdebug:$(TARGET_COPY_OUT_VENDOR)/bin/pvrdebug \
    vendor/amazon/mt8135-common/proprietary/vendor/bin/pvrsrvctl:$(TARGET_COPY_OUT_VENDOR)/bin/pvrsrvctl \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmwvmplugin.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/egl/libEGL_POWERVR_ROGUE.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_POWERVR_ROGUE.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_POWERVR_ROGUE.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/hw/gralloc.mt8135.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.mt8135.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/hw/memtrack.mt8135.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.mt8135.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/libIMGegl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libIMGegl.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/libPVRScopeServices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libPVRScopeServices.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L1.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/libglslcompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libglslcompiler.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpvrANDROID_WSEGL.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/libsrv_init.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsrv_init.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/libsrv_um.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsrv_um.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/libusc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libusc.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/libwvdrm_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L1.so \
    vendor/amazon/mt8135-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so
